---
- name: '[OCP4-AUTO-INSTALL] Configure an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
    - vault/vault.yml
  tasks:
    - name: debug
      shell: "ls -lhrt ~/.kube/"

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][WORKER-NODES] Configure Worker Nodes'
      include_role:
        name: "ocp4-post-worker-nodes"
      when:
        - worker_nodes is defined
        - worker_nodes | bool
